apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.labels.app }} 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type | default "LoadBalancer" }} # if we dont have service type we wl take the default
